### ISSUE TITLE
without gt_map

### ISSUE THREAD

**Issue by Silentbarber** [JokerJohn/Cloud_Map_Evaluation#4]
Hello, I am very interested in your evaluation work, but if I don't have a gt_map, only a lio map, how should I evaluate it? Can you give me some guidance

**Comment by Silentbarber** [comment]
The error is as follows：

**Comment by JokerJohn** [comment]
Hi, @Silentbarber 
Thank you for your interest in our evaluation work.
Metrics like **MME (Mean Map Entropy)** or **MPV (Mean Plane Variance)** can be used to evaluate a map without requiring ground truth point clouds. Their underlying principles are quite straightforward: from an information-theoretic perspective, if the information content in a map is higher, the map's entropy will be lower, indicating that points in the map are **more locally clustered**, which implies better local continuity. 

However, as the formula shows, these metrics only consider the local characteristics of points (using only the covariance matrix). Therefore, they cannot provide a fair evaluation when changes occur at a different scale or point cloud density. For example, comparing a map generated by LIO with one optimized through loop closure. There is a brief explanation of this in the experiments section of [my paper](https://arxiv.org/abs/2411.17928).

<img width="414" alt="image" src="https://github.com/user-attachments/assets/ec92eeef-0f66-42cf-b1ad-1155c0fa2d10" />

**Comment by Silentbarber** [comment]
> 您好，感谢您对我们的评估工作感兴趣。
> 
> **MME（平均地图熵）**或 **MPV（平均平面方差）**等指标可用于评估地图，而无需地面实况点云。它们的基本原理非常简单：从信息论的角度来看，如果地图中的信息内容较高，则地图的熵将较低，这表明地图中的点**更局部聚集**，这意味着更好的局部连续性。
> 
> 但是，如公式所示，这些指标仅考虑点的局部特征（仅使用协方差矩阵）。因此，当变化发生在不同的比例或点云密度时，它们无法提供公平的评估。例如，将 LIO 生成的 map 与优化的 through loop closure 进行比较。[在我论文](https://arxiv.org/abs/2411.17928)的实验部分对此进行了简要解释。
> 
> <img alt="image" width="414" src="https://private-user-images.githubusercontent.com/25702851/398656554-ec92eeef-0f66-42cf-b1ad-1155c0fa2d10.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUxOTc4MzYsIm5iZiI6MTczNTE5NzUzNiwicGF0aCI6Ii8yNTcwMjg1MS8zOTg2NTY1NTQtZWM5MmVlZWYtMGY2Ni00MmNmLWIxYWQtMTE1NWMwZmEyZDEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI2VDA3MTg1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRmOGY5MWU1MjVjYTIxNzBjOTY1MzM1NDI2MGYwOTU1OGYyYmVlZWVkMDU5OWRlN2FhMjhiNWE4NzFjMmYzNmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.wtwaDoYveKfhZFaMIqtnITipmkEVKkAGMr1j7sT3doA">

thank you！Wishing the paper a smooth progress！

**Comment by JokerJohn** [comment]
@Silentbarber the full version of codes released, pls check it
